### ISSUE TITLE
Players and Interval Duration

### ISSUE THREAD

**Issue by b1dr** [chejazi/points-challenge#4]
The main part of the game is clear. What I'm having a hard time with is the input format, I'll try to summarize the way I'm working on this right now and please correct me if I went about it wrong.

The algorithm takes the players' spending on each interval (I'm using a csv file where each line corresponds to a player, e.g. "1,0,0,1,0,0,0,0" will correspond to the amounts Alice spends throughout the game), the other input is the duration of intervals.

What the algorithm does is, after each interval had passed it will provide the points of each player from the previous N intervals.

I already have a working version that needs some modifications.

Also, suppose current interval 9 but the csv file contains only 6 intervals for each player, this pushes me to think that maybe another way of taking players input is expected, maybe ask the user to provide it after each interval.

**Comment by chejazi** [comment]
I created an example interface you can use.

https://github.com/chejazi/points-challenge/blob/master/example-skeleton.js

**Comment by chejazi** [comment]
> What the algorithm does is, after each interval had passed it will provide the points of each player from the previous N intervals.

You need to return the total points among all active players for a single historic interval. Note that iterating over each active player would violate the complexity constraint, as the number of players can greatly exceed the number N of intervals.
